### ISSUE TITLE
property name

### ISSUE THREAD

**Issue by TrySound** [postcss/postcss-mixins#1]
Does argument work for property name?

```css
@define-mixin item $prop {
	&-12 {
		$prop: 100%;
	}
	&-11 {
		$prop: 91.66666667%;
	}
	&-10 {
		$prop: 83.33333333%;
	}
	&-9 {
		$prop: 75%;
	}
	&-8 {
		$prop: 66.66666667%;
	}
	&-7 {
		$prop: 58.33333333%;
	}
	&-6 {
		$prop: 50%;
	}
	&-5 {
		$prop: 41.66666667%;
	}
	&-4 {
		$prop: 33.33333333%;
	}
	&-3 {
		$prop: 25%;
	}
	&-2 {
		$prop: 16.66666667%;
	}
	&-1 {
		$prop: 8.33333333%;
	}
}
```
