### ISSUE TITLE
Invalid output when using custom properties

### ISSUE THREAD

**Issue by alexgagnon** [postcss/postcss-mixins#116]
Hi! Loving this plugin, saved my life. However, I'm getting the following behaviour when using mixins in custom properties. I could be using the wrong syntax, but I believe I need to use $() when there's the trailing `-` after the variable. And yes, I am intentionally using a var with a fallback that is another var :)

```css
/* Input */
@define-mixin copy-font $type {
  font-size: var(--$(type)-size-override, var(--xsmall-copy-font-size));
}

body,
.p {
  @mixin copy-font copy;
}

/* Expected output */
body,
.p {
    font-size: var(--copy-size-override, var(--xsmall-copy-font-size));
}

/* Actual output */
body,
.p {
  font-size: , var(--xsmall-copy-font-size));
}

```

**Comment by ai** [comment]
I tested this snippet and got this output:

```css
.p {
        font-size: var(--copy-size-override, var(--xsmall-copy-font-size));
      }
```

Seems like you have another PostCSS plugin or CSS tool that change `var()`

---

[https://opencollective.com/postcss/](PostCSS OpenCollective)
