### ISSUE TITLE
Pseudo element not parsed properly in mixin function

### ISSUE THREAD

**Issue by mdings** [postcss/postcss-mixins#128]
Consider the basic setup below

```javascript
// postcss.config.js
const path = require('path');
module.exports = {
  plugins: [
    require('postcss-mixins')({ mixinsDir: path.join(__dirname, 'mixins') }),
    require('postcss-nested'),
    require('postcss-simple-vars'),
    require('postcss-hexrgba')
  ]
}
```

```javascript
// mixins/inter.js
module.exports = {
  '&::after': {
    content: '""',
    display: 'block',
    clear: 'both'
  }
}
```

```css
/* hero.module.css */
.Hero {
  opacity: 1;
  position: relative;
  background-color: rgba(#390099, 10%);
  @mixin inter;
}
```

yields the following result:
<img width="1019" alt="Schermafbeelding 2021-05-19 om 00 35 58" src="https://user-images.githubusercontent.com/1887262/118732216-3151f200-b83a-11eb-817c-08a4cd2d2cfa.png">

Any idea what's going on?
