### ISSUE TITLE
Converting SCSS mixin help

### ISSUE THREAD

**Issue by steffenmllr** [postcss/postcss-mixins#13]
Hey there, more a question than an issue:

I'm trying to convert a scss mixin to postcss that handles `:hover` selectors.
Is it possible to return a nested object as a mixin or how would you handle this ?

```scss

@mixin link-colors($normal, $hover: false, $active: false, $visited: false, $focus: false) {
  color: $normal;
  @if $visited {
    &:visited {
      color: $visited;
    }
  }
  @if $focus {
    &:focus {
      color: $focus;
    }
  }
  @if $hover {
    &:hover {
      color: $hover;
    }
  }
  @if $hover == false {
    &:hover {
      color: lighten($normal, 12%);
    }
  }
  @if $active {
    &:active {
      color: $active;
    }
  }
}
```

**Comment by ai** [comment]
I think custom plugin `postcss-link-colors` is a better solution:

```css
a {
    link-color: red, blue;
}
```
