### ISSUE TITLE
could I write a mixin for the values with postcss-mixin?

### ISSUE THREAD

**Issue by budarin** [postcss/postcss-mixins#138]
We need to have an ability to convert pixels to rem
Is there an ability to write mixin for values like this

```css
.some-selector {
  ...
  width: $rem(50);
  ...
}
```
to produce

```css
.some-selector {
  ...
  width: 3.125rem;
  ...
}
```
