### ISSUE TITLE
Doesn't work with postcss-custom-properties ?

### ISSUE THREAD

**Issue by jtomaszewski** [postcss/postcss-mixins#140]
Our example code:

```css
@import "../common/variables.css";

@define-mixin color $color {
  color: $color;
}

.spinner--color-teal1 {
  @mixin color #00a790;
}
.spinner--color-teal2 {
  @mixin color var(--color-teal);
}
.spinner--color-teal3 {
  color: var(--color-teal);
}
```

Current Output:

```css
.spinner--color-teal1 {
  color: #00a790;
}

.spinner--color-teal2 {
  color: var(--color-teal);
}

.spinner--color-teal3 {
  color: #00a790;
}
```

Expected Output:

```css
.spinner--color-teal1 {
  color: #00a790;
}

.spinner--color-teal2 {
  color: #00a790;
}

.spinner--color-teal3 {
  color: #00a790;
}
```

postcss.config.js :

```js
module.exports = {
  plugins: [
    require("postcss-import")(),
    require("postcss-mixins")(),
    require("postcss-custom-properties")({
      preserve: false,
    }),
    require("postcss-nesting")(),
    require("postcss-custom-media")(),
    require("autoprefixer")(),
  ],
};
```

Any idea what are we doing wrong?

Packages versions are up-to-date:

```json
    "postcss": "^8.4.5",
    "postcss-color-function": "^4.1.0",
    "postcss-color-mod-function": "^3.0.3",
    "postcss-custom-media": "^8.0.0",
    "postcss-custom-properties": "^11.0.0",
    "postcss-import": "^14.0.2",
    "postcss-mixins": "^9.0.1",
    "postcss-nesting": "^10.0.3",
```
