### ISSUE TITLE
A query on Tailwind theme functions, is this possible by defining mixin in JS ?

### ISSUE THREAD

**Issue by rhysmatthew** [postcss/postcss-mixins#159]
Hi, I understand this may not be possible but I thought I'd reach out for any insights. 

I'm trying to define a mixin that uses Tailwind theme functions like so to save me repeating lines: 

`@define-mixin btnBg $colour $hoverColour {
  background:
    linear-gradient(to right, $colour, $colour),
    linear-gradient(to right, $hoverColour, $hoverColour, $hoverColour);
}`

`@mixin btnBg theme('colors.offblack') theme('colors.purple.DEFAULT');`

However my output doesn't process the tailwind theme function within the mixin, I just get `background: linear-gradient(to right,$colour,$colour),linear-gradient(to right,$hoverColour,$hoverColour,$hoverColour);`. I've tried just passing a string also with the theme function within the 'define-mixin' but no luck there either.
 
Is there a way to write this in JS at all or ensure that the tailwind theme function runs before the mixin plugin? I understand I need to figure this out myself but any pointers would be appreciated. Equally if it's not possible then please just close the issue.

Thanks,

**Comment by ai** [comment]
Can you disable all plugins, enable only `postcss-mixins` and show me the output of:

```css
@define-mixin btnBg $colour $hoverColour {
  background: linear-gradient(to right, $colour, $colour),
    linear-gradient(to right, $hoverColour, $hoverColour, $hoverColour);
}

a {
  @mixin btnBg theme('colors.offblack') theme('colors.purple.DEFAULT');
}
```
