### ISSUE TITLE
Unexpected behaviour with CSS native nested child selector

### ISSUE THREAD

**Issue by osvaldasvalutis** [postcss/postcss-mixins#171]
Problem: property/value pair defined in the mixin are removed from nested (CSS native) children selectors and placed below the mixin's output.

Simplified example code:

```css
@define-mixin container {
  width: 100%;
}

.container {
  @mixin container;

  & div {
    width: 100%;
    color: red;
  }
}
```

Expected output:

```css
.container {
  width: 100%;

  & div {
    width: 100%;
    color: red;
  }
}
```

Generated production output:

```css
.container {
  width: 100%;
  width: 100%;

  & div {
    color: red;
  }
}
```

So basically the `width: 100%;` was relocated up to the parent selector.

This only happens in production build and when the mixin is used. This applies to all same property/value pair that goes in both mixin and any child selector, even on multi-level nest, e.g.:

```css
.container {
  width: 100%;

  & div {
    width: 100%;
    color: red;

    & span {
      width: 100%;
      color: blue;
    }
  }
}

/* output */

.container {
  width: 100%;
  width: 100%;
  width: 100%;

  & div {
    color: red;

    & span {
      color: blue;
    }
  }
}
```

`postcss-mixins` is the first in the config list:

```js
module.exports = {
  plugins: {
    "postcss-mixins": {
      mixinsFiles: [path.join(__dirname, `postcss/mixin.*.css`)],
    },
    ...
}
```

Tested with other plugins removed – same output.

```
"next": "14.2.16",
"postcss-mixins": "^11.0.3"
```

**Comment by ai** [comment]
When I run `postcss-mixins` without any plugin in pure JS script, I can’t reproduce this bug. Seems like you have an issue from some other tool:

```js
let postcss = require('postcss')
let plugin = require('./')

let css = `
@define-mixin container {
  width: 100%;
}

.container {
  @mixin container;

  & div {
    width: 100%;
    opacity: 1;
  }
}`

let result = postcss([plugin]).process(css, {
  from: 'tst.js'
})

console.log(result.css)
```

This code generates:

```css
.container {
  width: 100%;

  & div {
    width: 100%;
    opacity: 1;
  }
}
```

Which looks correct.
