### ISSUE TITLE
Allow to use = to define a mixin and + to use it

### ISSUE THREAD

**Issue by Grawl** [postcss/postcss-mixins#2]
Like it works in Sass. It's a cool shorthand and I like to use it with tabbed syntax to write less & do more :muscle: 

So instead of

```css
@define-mixin icon $network $color {
    .icon.is-$(network) {
        color: $color;
    }
    .icon.is-$(network):hover {
        color: white;
        background: $color;
    }
}

@mixin icon twitter blue;
@mixin icon youtube red;
```

I suggest to allow next:

```css
=icon $network $color {
    .icon.is-$(network) {
        color: $color;
    }
    .icon.is-$(network):hover {
        color: white;
        background: $color;
    }
}

+icon twitter blue;
+icon youtube red;
```
