### ISSUE TITLE
How to pass arguments containing spaces?

### ISSUE THREAD

**Issue by Francisc** [postcss/postcss-mixins#32]
Hi,

I want to pass in an argument that contains spaces.
I'm passing in a selector, e.g. `.some-container .some-element`.

Is there a way of doing that?

**Comment by ai** [comment]
Write a custom PostCSS plugin :-). This plugin is for real simple DRY cases, because I believe that CSS should be simple, and should not contains programming statement. CSS should be declarative, all magic should be inside JS

**Comment by ai** [comment]
Also you can write JS mixin and unquote selector in JS

**Comment by Francisc** [comment]
Here's an example:

```
@define-mixin test-mixin $selector
{
   $(selector) i
   {
      transition:all 1yr ease-in-out;
   }
}
```

How can I pass `.some-container .some-element` as the `$selector` argument?

**Comment by Francisc** [comment]
Just saw your answer. I don't think the example above is complicated.
You could even say I'm declaring the selector, it's not a programming statement.
And it's for DRYness that I need it.
Otherwise I need to specify the contents of it in many other places.

**Comment by ai** [comment]
@Francisc what exactly task you want to solve?

Because for that `transition` example, the best way is to:

```css
@define-mixin test-mixin
{
  i
  {
      transition:all 1yr ease-in-out;
   }
}

.test .one {
  @mixin test-mixin;
}
```

**Comment by Francisc** [comment]
You misread the code snippet.
I want to increase the selector specificity by passing in a `$(selector)`, e.g.
```
.some-container .some-element i {...}
```

Keep in mind it's just for illustration, not real-life code.

**Comment by ai** [comment]
@Francisc we have special [postcss-increase-specificity](https://github.com/MadLittleMods/postcss-increase-specificity) plugin for increase specificity cases :).

**Comment by ai** [comment]
In Sass everything is done my mixins. In PostCSS it is not. Often is better to write a plugin. But writing a plugin requires to more thinking. This is why I ask you about what exactly you want to do.

`postcss-mixin` is not to write magic like increase specificity, prefixes and many other things. If you can explain me your task better, I will suggest the best way to do it.

**Comment by Francisc** [comment]
I don't want to increase specificity just to have it increased which is what that plugin seems to do.
Specificity should always be low. But sometimes just `i` is too low.

I could write a plugin, but for this particular case, it should be part of postcss-mixin.
The above was just an example, maybe I should have just said "I would like to be able to pass arguments that contain spaces", without tying it to my particular case where I want to pass in a selector since that is only a string which has a space.

Do you disagree that one should be able to write postcss-mixins with arguments that can contain space characters?

**Comment by ai** [comment]
@Francisc OK, let’s I write a very hacky way how to do it in `postcss-mixin`:

```js
# mixins/test-mixin.js

module.exports = function (selector) {
    css = { };
    css[ selector.splice(1, -2) ] = {
        transition: 'all 1yr ease-in-out'
    }
    return css;
}
```

Then add `mixins/` dir to `mixinsDir` option and JS mixin `test-mixin` will be loaded automatically.

**Comment by ai** [comment]
@Francisc but you miss my main point. This is wrong, very wrong way. We live to many years in Sass mind box and think only in mixins terms. Look into Autoprefixer, CSS Modules, Font Magician, cssnext. It is great example, why we must stop to think in mixins way.

I wrote a lot of Sass code. And I can tell 100% sure, `unqoute()` and other mixins magic in CSS is very bad way. It redue maintability. Most of developers will think that mixins are just black box and will avoid to read/edit them.

**Comment by ai** [comment]
For example, maybe you should write plugin, that will add selector prefix by file name. Like add `.component-a` to every selector in `component-a/index.css` file.

Or use postcss-nested:

```css
.component-a {
    i {
        transition: all 1yr ease-in-out
    }
}
```

Or something else, if you will tell me what exactly task you want to solve.

**Comment by Francisc** [comment]
I agree in part with what you are saying, but things like vars (custom properties) and nesting were popularized in pre-processors like Sass and are now being spec`ed.

What I am trying to do is have a mixin for responsive tables so that code is DRYer.
```CSS
/*Make table elements stack*/
$(selector),
$(selector) thead,
$(selector) tfoot,
$(selector) tbody,
$(selector) tr,
$(selector) th,
$(selector) td
{
	display:block;
}

/*Get table header out of the way*/
$(selector) thead
{
	position:absolute;
	top:-9999px;
	left:-9999px;
	width:10px;
	height:10px;
}
```

This would be reused in media queries.
```
@media(min-width:760px){
   @mixin .data-list table
}
...
@media(min-width:1000px){
   @mixin .another-container .another-table
}
```

Otherwise I'd have to repeat those styles multiple times (twice in the example above) which is also bad for maintainability.

**Comment by ai** [comment]
PostCSS is not a Sass ;). Because this complicated code in CSS is source of Sass problems.

Here is a PostCSS way for this case:

```css
@use postcss-nested;
@use postcss-mixins;

@define-mixin styled-table {
    &,
    thead,
    tfoot,
    tbody,
    tr,
    th,
    td
    {
        display:block;
    }

    thead
    {
        position:absolute;
        top:-9999px;
        left:-9999px;
        width:10px;
        height:10px;
    }
}

@media(min-width:760px){
    .data-list table {
        @mixin styled-table;
    }
}
...
@media(min-width:1000px){
   .another-container .another-table {
        @mixin styled-table;
    }
}
```
