### ISSUE TITLE
Default if value is empty

### ISSUE THREAD

**Issue by MadLittleMods** [postcss/postcss-mixins#33]
When nesting mixins, passing along variable that is not defined, should also be undefined and default in the nested mixin.

Currently it seems to fill it with a blank value which makes it not use the default fallback value.

### [Demo](https://tonicdev.com/mlm/564217b66ca5f20c0078bc3f)

```css
@define-mixin style-links $color: #f00 {
    foo: $color;
}

@define-mixin format-content $color {
    @mixin style-links $color;
}

.foo {
    @mixin format-content;
}

.bar {
    @mixin format-content #0ff;
}
```

I would expect:

```css
.foo {
    foo: #f00;
}

.bar {
    foo: #0ff;
}
```

But currently the output is:

```css
.foo {
    foo: ;
}

.bar {
    foo: #0ff;
}
```
