### ISSUE TITLE
mixin-content

### ISSUE THREAD

**Issue by stephenway** [postcss/postcss-mixins#40]
Having an issue pretty consistently where I try to use `@mixin-content` and can never get it to replace with what I insert into the `@mixin` and it leaves the `@mixin-content` in the resulting CSS output.

I ran `gulp test` on a clone of this repo and that test comes up fine.

Here is my processors order:

``` js
        var processors = [
                cssimport,
                mixins,
                simplevars,
                nested,
                extend
        ];
```

**Comment by ai** [comment]
Show me please a CSS input and output

**Comment by stephenway** [comment]
Importing this https://github.com/stylep/stylep-card/blob/master/index.css
into this https://github.com/stylep/stylep-card/blob/master/example/index.css
which gives me this https://github.com/stylep/stylep-card/blob/master/example/build/index.css

**Comment by ai** [comment]
Can you show some small example? Input, output, expected output? (Sorry, I had too hard party after dotCSS yesterday)

**Comment by stephenway** [comment]
No problem, sounds like you had fun! :smile:

Input
```css
@define-mixin card-solid
  $color-passive: #f7f7f7,
  $color-text: #444,
  $radius-size: 0,
  $shadow: 0 2px 2px rgba(0, 0, 0, .4)
{
  background-color: $color-passive;
  border-radius: $radius-size;
  box-shadow: $shadow;
  color: $color-text;
  @mixin-content;
}

.card--solid {
  @mixin card-solid {
    color: green;
  }
}
```

Output
```css
.card--solid {
  background-color: #f7f7f7;
  border-radius: 0;
  box-shadow: 0 2px 2px rgba(0, 0, 0, .4);
  color: #444;
  @mixin-content
}
```

Expected output
```css
.card--solid {
  background-color: #f7f7f7;
  border-radius: 0;
  box-shadow: 0 2px 2px rgba(0, 0, 0, .4);
  color: #444;
  color: green;
}
```
