### ISSUE TITLE
Color definitions break params

### ISSUE THREAD

**Issue by mikestopcontinues** [postcss/postcss-mixins#41]
When I only use one param, I can get hsl() color definitions to work, but when I use two, it breaks. It looks like it might parse the commas within the vars as separators. It also doesn't work when I specify the default value of `$blend: var(--white)`.

```css
:root {
  --white: hsl(0, 0%, 100%);
  --gray: hsl(0, 0%, 50%);
}

@define-mixin linkColorBlend $color, $blend {
  color: $color;

  &:hover {
    color: color($color blend($blend 50%));
  }
}

.link {
  @mixin linkColorBlend var(--gray), white;
}
```

I get this error message:

```
Module build failed: Error: /Users/msc/Sites/msc.com/modules/www/Styles/Mixins/LinkMixins.css:18:5: Unable to parse color from string "hsl(0,"
    at /Users/msc/Sites/msc.com/modules/www/Styles/Mixins/LinkMixins.css:18:5
    at Object.Color (/Users/msc/Sites/msc.com/node_modules/color/index.js:33:10)
    at Object.exports.blend (/Users/msc/Sites/msc.com/node_modules/css-color-function/lib/adjusters.js:39:15)
    at /Users/msc/Sites/msc.com/node_modules/css-color-function/lib/convert.js:56:20
    at Array.forEach (native)
    at toRGB (/Users/msc/Sites/msc.com/node_modules/css-color-function/lib/convert.js:42:7)
    at Object.convert (/Users/msc/Sites/msc.com/node_modules/css-color-function/lib/convert.js:28:10)
    at transformColor (/Users/msc/Sites/msc.com/node_modules/postcss-color-function/index.js:49:43)
    at transformColorValue (/Users/msc/Sites/msc.com/node_modules/postcss-color-function/index.js:20:16)
    at Object.tryCatch [as try] (/Users/msc/Sites/msc.com/node_modules/postcss-message-helpers/index.js:53:12)
    at transformDecl (/Users/msc/Sites/msc.com/node_modules/postcss-color-function/index.js:19:31)
 @ ./modules/www/ArchiveLink/ArchiveLink.css 4:14-216 13:2-17:4 14:20-222
```
