### ISSUE TITLE
Option to turn off arg space separation

### ISSUE THREAD

**Issue by stephenway** [postcss/postcss-mixins#42]
I understand this is going away in the next version, but it is throwing an error for the first argument for padding where it should take 1-4 space separated values in one argument. It would be nice to silence or turn that off until the next version comes out.

**Comment by ai** [comment]
I miss the problem. Can show it in code examples?

**Comment by stephenway** [comment]
Yep, just a simple box mixin for example 

```css
@define-mixin box $padding: 0, $margin: 0 {
  padding: $padding;
  margin: $margin;
}

.foo {
  @mixin box .5em 1em;
}
```

This forces me to try using the second argument default value to avoid the false warning.

```css
.bar {
  @mixin box .5em 1em, 0;
}
```

However this doesn't seem to resolve the issue.
