### ISSUE TITLE
Complex mixins with an object as argument

### ISSUE THREAD

**Issue by ayrton** [postcss/postcss-mixins#45]
Love the plugin, but I'm more or less struggling a little to write more complex mixins.

Can you somehow create a mixin that accepts an object as argument:

```js
function(mixin, selector, {background, color}) {
}

// or in non es6:
function(mixin, selector, args) {
}
```

In the css I would imagine it looks something like this:

```css
a {
  @mixin foo '&:hover', { background: 'yellow', color: 'red' };
}
```

I've tried searching the docs and tests but didn't find much, my knowledge of post css internals is somewhat also limited so digging inside the code did not help me find the answer (yet).
