### ISSUE TITLE
Passing value to named param in a mixin with multiple params

### ISSUE THREAD

**Issue by ryexley** [postcss/postcss-mixins#54]
I'm having trouble figuring out how to pass a value to a specific param in to a mixin that has multiple params defined. For example, I have an unstyled list mixin:

```css
@define-mixin unstyled-list( $margin: 0, $padding: 0, $itemMargin: 0, $itemPadding: 0 ) {
  @mixin clearfix;
  list-style-type: none;
  margin: $margin;
  padding: $padding;
  @mixin-content;

  & > li {
    margin: $itemMargin;
    padding: $itemPadding;
  }
}
```

How would I apply this mixin providing a value for _just_ the `$padding` param, and taking the defaults for the others? Having trouble figuring out the correct syntax for this. Any help would be greatly appreciated.
