### ISSUE TITLE
What about defining default params?

### ISSUE THREAD

**Issue by tunnckoCore** [postcss/postcss-mixins#6]
i'm trying to port some scss to postcss and cant find solution for this use case

```scss
@mixin grid-overlay($color: black, $px-offset: false) {
  body {
    background: linear-gradient(to top, rgba($color, .1) 5%, white 5%);
    background-size: 100% ($line-height-ratio) + em;
    @if($px-offset) {
      background-position: 0 $px-offset + px;
    }
  }
}
```

**Comment by tunnckoCore** [comment]
or more advanced
```scss
@mixin t-h2() {
  $local-min-font: $min-font * (math-pow($header-ratio, 1.4));
  $local-max-font: $max-font * (math-pow($header-ratio, 1.4));

  font-size: $local-min-font;
  @if ($vertical-rhythm) {
    margin-top: (($line-height-ratio * $min-font) / ($local-min-font / 1.25)) + em;
    line-height: (($line-height-ratio * $min-font) / ($local-min-font / 1.5)) + em;
    margin-bottom: (($line-height-ratio * _strip-units($min-font)) / (_strip-units($local-min-font) / .25) * (1 + (3 / _strip-units($local-min-font)))) + em;
  } @else {
    margin-top: 0;
    line-height: 1.2em;
    margin-bottom: .25em;
  }

  @media (min-width: $min-width) {
    font-size: calc( #{$local-min-font} + (#{_strip-units($local-max-font)} - #{_strip-units($local-min-font)}) * ((100vw - #{$min-width}) / (#{_strip-units($max-width)} - #{_strip-units($min-width)})) );
  }

  @media (min-width: $max-width) {
    font-size: $local-max-font;
    @if ($vertical-rhythm) {
      margin-top: (($line-height-ratio * $max-font) / ($local-max-font / 1.25)) + em;
      line-height: (($line-height-ratio * $max-font) / ($local-max-font / 1.5)) + em;
      margin-bottom: (($line-height-ratio * _strip-units($max-font)) / (_strip-units($local-max-font) / .25) * (1 + (3 / _strip-units($local-max-font)))) + em;
    }
  }
}
```
