### ISSUE TITLE
postcss-mixins@5.2.0 doesn't work?

### ISSUE THREAD

**Issue by graphan** [postcss/postcss-mixins#61]
I have the following mixin:

```css
@define-mixin icon $top, $left, $width, $number {
  .icon-$(number) {
    background: url(../../images/icons1.png) no-repeat $top $left;
    width: $width;
    height: 35px;
    display: inline-block;
    text-align: center;
    margin-bottom: 1em
  }
}

@mixin icon -46px, -14px, 28px, 1
@mixin icon -96px, -14px, 28px, 2
@mixin icon -145px, -14px, 35px, 3
@mixin icon -46px, -14px, 28px, 4
```

This code does not generate four class definitions. The only thing that is generated is:
```css
.icon-1
@mixin icon -96px {
  background: url(...) no-repeat -46px -14px;
  width: 28px;
  height: 35px;
  display: inline-block;
  text-align: center;
  margin-bottom: 1em
}
```
Unfortunately, it is no valid css.

Maybe, I am doing something wrong, but according to Readme, I think that it shoud generate four classes. It is my `webpack` setup:
```js
postcss: [
    postcssImport({
      addDependencyTo: webpack
    }),
    postcssMixins(),
    postcssCSSNext({
      browsers: ['last 10 versions']
    })
  ],
```
Is `postcssMixins()` placed correctly?
