### ISSUE TITLE
influenced other attribute

### ISSUE THREAD

**Issue by evanyangg** [postcss/postcss-mixins#69]
### like this:

first mixin:

```scss
@define-mixin height-line-height $height, $line-height {
  height: $height;
  line-height: $line-height;
  [data-dpr="2"] & {
    height: calc($height * 2);
    line-height: calc($line-height * 2);
  }
  [data-dpr="3"] & {
    height: calc($height * 3);
    line-height: calc($line-height * 3);
  }
}
```
second mixin:
```scss
@define-mixin font-dpr $font-size {
  font-size: $font-size;
  [data-dpr="2"] & {
    font-size: calc($font-size * 2);
  }
  [data-dpr="3"] & {
    font-size: calc($font-size * 3);
  }
}
```
### my code:
![image](https://cloud.githubusercontent.com/assets/22952321/25229696/d58918f8-2603-11e7-930b-55f5372eb760.png)
and chrome show:
![image](https://cloud.githubusercontent.com/assets/22952321/25229706/ea933300-2603-11e7-8263-ddf098236f25.png)
vertical-align  is not working,  i change this order, like this:
```scss
     vertical-align: top;
     display: inline-block;
     @mixin font-dpr 48px;
     /*@mixin height-line-height 48px, 48px;*/
```
```scss
    vertical-align: top;
    display: inline-block;
    font-size: 48px;
```
its ok;
when i use two mixins ;
### case 1:
```scss
    vertical-align: top;
    display: inline-block;
    @mixin font-dpr 48px;
    @mixin height-line-height 48px, 48px;
```
got
```scss
    vertical-align: top;
    display: inline-block;
    font-size: 48px;
    line-height: 48px;
```
### case 2:
```scss
     display: inline-block;
     @mixin font-dpr 48px;
     @mixin height-line-height 48px, 48px;
     vertical-align: top;
```
got
```scss
    display: inline-block;
    font-size: 48px;
    line-height: 48px;
```
### case 3
```scss
    display: inline-block;
    @mixin font-dpr 48px;
    vertical-align: top;
    @mixin height-line-height 48px, 48px;
```
```scss
    display: inline-block;
    font-size: 48px;
    height: 48px;
    line-height: 48px;
```
i very like this mixin tools , i know you will help me :)
