### ISSUE TITLE
use with postcss-custom-properties

### ISSUE THREAD

**Issue by Memoyr** [postcss/postcss-mixins#82]
Hi ,
Is it normal that this isn't working while using with postcss-custom-properties ? It strips out everything from the rule value but not the actual argument.

```
@define-mixin generate $size {
    font-size: var(--text$(size);
}
.test {
  @mixin generate sm;
}
```
**output :**

```
.test {
   font-size: sm;
}
```

thanks

**Comment by ai** [comment]
Input should be:

```css
@define-mixin generate $size {
  font-size: var(--text$(size));
}
.test {
  @mixin generate sm;
}
```

What is you PostCSS config?
