### ISSUE TITLE
Is it possibile using custom variables in mixins

### ISSUE THREAD

**Issue by timhecker** [postcss/postcss-mixins#84]
Hi,
I would like to use a mixin with custom variables like parameters, something like this:

```css
@define-mixin wrapper-helper --width: 1280px {
	max-width: var(--width);
	margin: 0 auto;
}
```

Is this possible only with [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) plugin?
